#!/bin/bash

RED=`tput setaf 1`
GREEN=`tput setaf 2`
NC=`tput sgr0`

if [ "$#" -ne 3 ]; then
    echo "${RED}Error:${NC} expected 3 parameters: project, route and port"
    exit 1
fi

if [ ! -f "/var/www/vhosts/system/$1.sixhands.co/conf/vhost_ssl.conf" ]; then
	echo "${RED}Error:${NC} config file not found: /var/www/vhosts/system/$1.sixhands.co/conf/vhost_ssl.conf"
	exit 1
fi

printf "<Location $2>\n   ProxyPass http://localhost:$3/\n   ProxyPassReverse http://localhost:$3/\n</Location>\n" > "/var/www/vhosts/system/$1.sixhands.co/conf/vhost_ssl.conf"
systemctl reload apache2

echo "${GREEN}Proxy for project '$1' added: $2 -> $3${NC}"