#!/bin/bash

RED=`tput setaf 1`
GREEN=`tput setaf 2`
NC=`tput sgr0`

if [ "$#" -ne 1 ]; then
    echo "${RED}Error:${NC} expected 1 parameter: project name"
    exit 1
fi

if [ ! -f "/var/www/vhosts/system/$1.sixhands.co/conf/vhost_ssl.conf" ]; then
	echo "${RED}Error:${NC} config file not found: /var/www/vhosts/system/$1.sixhands.co/conf/vhost_ssl.conf"
	exit 1
fi

printf "" > "/var/www/vhosts/system/$1.sixhands.co/conf/vhost_ssl.conf"
systemctl reload apache2

echo "${GREEN}Proxy rules for project '$1' removed${NC}"