#!/bin/bash

RED=`tput setaf 1`
GREEN=`tput setaf 2`
NC=`tput sgr0`
CUR_DIR=$(pwd)

COMPOSE_FILE=./docker-compose.yml

if [ ! -f "$COMPOSE_FILE" ]; then
	echo "${RED}Error:${NC} docker-compose.yml not found"
	exit 1
fi

if [[ ! $CUR_DIR == *"/var/www/vhosts/"* ]]; then
	echo "${RED}Error:${NC} script must be executed only in /var/www/vhosts/* directory"
	exit 1
fi


# Check if a user can MOUNT specified volumes in Docker
# $1: path to a docker-compose file
# $2: minimal directory that can be mounted
VOLUMES_OK=`python3 /bin/docker/check_volumes.py "$COMPOSE_FILE" "$CUR_DIR"`


if [ ! $VOLUMES_OK = 0 ]; then
	echo "${RED}Error:${NC} user has no permission to mount specified directory"
	exit 1
fi

echo "${GREEN}Cheks are done. Docker-compose started ...${NC}"

if [ "$1" = "--no-build" ]; then
	echo "${GREEN}Running container without Rebuilding ...${NC}"
	docker-compose -f $COMPOSE_FILE up -d
else
	echo "${GREEN}Rebuilding image ...${NC}"
	docker-compose -f $COMPOSE_FILE up -d --build
fi
