#!/bin/bash

RED=`tput setaf 1`
GREEN=`tput setaf 2`
NC=`tput sgr0`
CUR_DIR=$(pwd)

COMPOSE_FILE=./docker-compose.yml

if [ ! -f "$COMPOSE_FILE" ]; then
	echo "${RED}Error:${NC} docker-compose.yml not found"
	exit 1
fi

docker-compose logs -f $COMPOSE_FILE
